import {
    beef,
    chicken,
    corn,
    fish,
    flour,
    milk,
    potato,
    rice,
    shrimp,
} from "../../../public/images";
import { Shop, Item, Ingredient } from "../types";
import { Category } from "../types";

export const Shops: Shop[] = [
    { id: 1, shopName: "Cow Grade A", rating: 4.5 },
    { id: 2, shopName: "Veggies", rating: 4.2 },
];

export const initialItems: Item[] = [
    {
        ingredientId: 1,
        amount: 200,
        price: 100,
        unit: "kg",
        shopId: 1,
    },
    {
        ingredientId: 2,
        amount: 200,
        price: 2,
        unit: "kg",
        shopId: 1,
    },
    {
        ingredientId: 3,
        amount: 200,
        price: 150,
        unit: "kg",
        shopId: 1,
    },
    {
        ingredientId: 4,
        amount: 200,
        price: 250,
        unit: "kg",
        shopId: 1,
    },
    {
        ingredientId: 5,
        amount: 200,
        price: 180,
        unit: "kg",
        shopId: 1,
    },
    {
        ingredientId: 6,
        amount: 200,
        price: 160,
        unit: "kg",
        shopId: 1,
    },
    {
        ingredientId: 7,
        amount: 200,
        price: 300,
        unit: "kg",
        shopId: 1,
    },
    {
        ingredientId: 11,
        amount: 200,
        price: 80,
        unit: "kg",
        shopId: 1,
    },
    {
        ingredientId: 12,
        amount: 200,
        price: 80,
        unit: "kg",
        shopId: 1,
    },
    {
        ingredientId: 13,
        amount: 200,
        price: 80,
        unit: "kg",
        shopId: 1,
    },
    {
        ingredientId: 14,
        amount: 200,
        price: 80,
        unit: "kg",
        shopId: 1,
    },
    {
        ingredientId: 21,
        amount: 200,
        price: 50,
        unit: "kg",
        shopId: 1,
    },
    {
        ingredientId: 22,
        amount: 200,
        price: 50,
        unit: "kg",
        shopId: 1,
    },
    {
        ingredientId: 23,
        amount: 200,
        price: 50,
        unit: "kg",
        shopId: 1,
    },
    {
        ingredientId: 24,
        amount: 200,
        price: 50,
        unit: "kg",
        shopId: 1,
    },
    {
        ingredientId: 31,
        amount: 200,
        price: 100,
        unit: "kg",
        shopId: 1,
    },
    {
        ingredientId: 32,
        amount: 200,
        price: 100,
        unit: "kg",
        shopId: 1,
    },
    {
        ingredientId: 33,
        amount: 200,
        price: 100,
        unit: "kg",
        shopId: 1,
    },
    {
        ingredientId: 41,
        amount: 200,
        price: 140,
        unit: "kg",
        shopId: 1,
    },
    {
        ingredientId: 42,
        amount: 200,
        price: 140,
        unit: "kg",
        shopId: 1,
    },
    {
        ingredientId: 43,
        amount: 200,
        price: 140,
        unit: "kg",
        shopId: 1,
    },
    {
        ingredientId: 44,
        amount: 200,
        price: 140,
        unit: "kg",
        shopId: 1,
    },
    {
        ingredientId: 51,
        amount: 200,
        price: 170,
        unit: "kg",
        shopId: 1,
    },
    {
        ingredientId: 52,
        amount: 200,
        price: 170,
        unit: "kg",
        shopId: 1,
    },
    {
        ingredientId: 53,
        amount: 200,
        price: 170,
        unit: "kg",
        shopId: 1,
    },
];

export const Ingredients: Ingredient[] = [
    { id: 1, image: beef, category: Category.Meat, name: "beef" },
    { id: 2, image: chicken, category: Category.Meat, name: "chicken" },
    { id: 3, image: beef, category: Category.Meat, name: "pork" },
    { id: 4, image: beef, category: Category.Meat, name: "lamb" },
    { id: 5, image: fish, category: Category.Meat, name: "fish" },
    { id: 6, image: shrimp, category: Category.Meat, name: "shrimp" },
    { id: 7, image: beef, category: Category.Meat, name: "crab" },

    { id: 11, image: beef, category: Category.Fruits, name: "apple" },
    { id: 12, image: beef, category: Category.Fruits, name: "orange" },
    { id: 13, image: beef, category: Category.Fruits, name: "watermelon" },
    { id: 14, image: beef, category: Category.Fruits, name: "mango" },

    { id: 21, image: potato, category: Category.Vegatables, name: "carrot" },
    { id: 22, image: potato, category: Category.Vegatables, name: "potato" },
    { id: 23, image: potato, category: Category.Vegatables, name: "tomato" },
    {
        id: 24,
        image: potato,
        category: Category.Vegatables,
        name: "morning glory",
    },

    { id: 31, image: milk, category: Category.Dairy, name: "milk" },
    { id: 32, image: milk, category: Category.Dairy, name: "cheese" },
    { id: 33, image: milk, category: Category.Dairy, name: "cream" },

    { id: 41, image: rice, category: Category.Grains, name: "rice" },
    { id: 42, image: rice, category: Category.Grains, name: "wheat" },
    { id: 43, image: corn, category: Category.Grains, name: "corn" },
    { id: 44, image: flour, category: Category.Grains, name: "flour" },

    { id: 51, image: beef, category: Category.Spices, name: "pepper" },
    { id: 52, image: beef, category: Category.Spices, name: "salt" },
    { id: 53, image: beef, category: Category.Spices, name: "paprika" },
];
